services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  rclone:
    image: rclone/rclone:latest
    command: rcd --rc-addr=:5572 --rc-user=${RCLONE_USERNAME} --rc-pass=${RCLONE_PASSWORD}
    volumes:
      - rclone_config:/config
      - bucket:/data
    restart: unless-stopped

  api:
    # image: ghcr.io/nogringo/blone:latest
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BLOSSOM_API_PORT}:3000"
    volumes:
      - bucket:/data
    restart: unless-stopped
    depends_on:
      - db
      - rclone
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      RCLONE_USERNAME: ${RCLONE_USERNAME}
      RCLONE_PASSWORD: ${RCLONE_PASSWORD}
      BLOSSOM_API_DOMAIN: ${BLOSSOM_API_DOMAIN}
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}

volumes:
  postgres_data:
  rclone_config:
  bucket:
