services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # rclone:
  #   image: rclone/rclone:latest
  #   container_name: rclone-api
  #   command: rcd --rc-web-gui --rc-addr=:5572 --rc-user=admin --rc-pass=admin
  #   ports:
  #     - "5572:5572"
  #   volumes:
  #     - rclone_config:/config
  #     - ./:/data
  #   restart: unless-stopped

# volumes:
#   pgdata:
#   rclone_config:
#   rclone_data:
#   postgres_data: